version: '3.8'
services:
  db:
    image: postgres
    container_name: task_management_system_postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_management_system
    ports:
      - "5432:5432"